### PR TITLE
adding checkItemExists function

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by jread-usgs** [comment]
@mhines-usgs I think you need to `git pull git@github.com:USGS-R/hazardItems.git master` and fix conflicts

**Comment by mhines-usgs** [comment]
Yeah I see that. I'll get help from Sibley because I have no idea what I'm doing.

**Comment by mhines-usgs** [comment]
@jread-usgs PS I am getting an error with this checkItemExists call, but I feel like it should work. Just wanted to have you check it too. I wasn't sure if it was because I'm not on the network or because it makes no sense? 

" Error in function (type, msg, asError = TRUE)  : 
  Operation timed out after 5007 milliseconds with 0 bytes received "

**Comment by jread-usgs** [comment]
that doesn't sound good to me. will look into it. thx

**Comment by mhines-usgs** [comment]
ok, it might be the network, it errors so fast. i will try when I get my
access card in my hand later too.


~~~~~

Megan K. Hines

Contractor, Cherokee Nation Technology Solutions
Center for Integrated Data Analytics
USGS Wisconsin Water Science Center
8505 Research Way
Middleton, WI 53562
Office: 608-821-3917
mhines@usgs.gov

On Tue, Apr 21, 2015 at 12:28 PM, Jordan S Read <notifications@github.com>
wrote:

> that doesn't sound good to me. will look into it. thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/hazardItems/pull/73#issuecomment-94879999>.
>

**Comment by jread-usgs** [comment]
Seemed to work fine for me, so probably just kill the auth part of this and commit that?

**Comment by jread-usgs** [comment]
Failed on 
```R
serviceEndpoint <- 'http://marine.usgs.gov/coastalchangehazardsportal/data/item/CAkR645'
thumb.service(serviceEndpoint)
Error in item.json$bbox : object of type 'externalptr' is not subsettable
Calls: thumb.service -> getUniqueBBoxIDs -> unlist
Execution halted
```
odd

**Comment by jread-usgs** [comment]
` Error in function (type, msg, asError = TRUE)  : 
  Recv failure: Connection reset by peer ` for me

**Comment by jread-usgs** [comment]
@mhines-usgs the app looks down to me. :zap:

**Comment by mhines-usgs** [comment]
Weird. Ok, thanks brah

**Comment by jread-usgs** [comment]
app was down, @isuftin fixed it. Now kicking the CI off again to make sure we are good on the package build.

**Comment by jread-usgs** [comment]
@mhines-usgs if you have time, `checkItemsExists` should be easy to write a couple of tests for...

**Comment by mhines-usgs** [comment]
Will do!

**Pull request merged**
